#!/usr/bin/env python3
"""Add a text-defined visual style after a square representative image is available."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from style_library_import import (
    create_style_assets,
    get_next_style_number,
    rebuild_and_validate,
    update_manifest,
    update_markdown_source,
    update_model_capabilities,
    update_readme_and_skill,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-name", help="Chinese/original style label; optional for a text-only original style")
    parser.add_argument("--generation-name", help="English generation style name; optional for a text-only original style")
    parser.add_argument("--traits", default="", help="Positive concrete visual traits")
    parser.add_argument("--traits-file", type=Path, help="File containing traits text")
    parser.add_argument("--raw-traits", action="store_true", help="Preserve traits exactly as provided without positive_traits filtering")
    parser.add_argument("--image", type=Path, help="Representative source image, supplied or generated by the Skill")
    parser.add_argument("--dry-run", action="store_true", help="Print the resolved registration policy without modifying the library")
    return parser.parse_args()


def positive_traits(value: str) -> str:
    """Keep only concrete positive traits for both metadata and prompting."""
    parts = [part.strip() for part in value.replace("。", "；").split("；")]
    cleaned = []
    for part in parts:
        if not part:
            continue
        for marker in ("避免", "不要", "不准", "禁止"):
            if marker in part:
                part = part.split(marker, 1)[0]
        part = re.sub(r"无(?:写实纹理|精细材质|真实纹理)[、，]?", "", part)
        part = re.sub(r"[、，]\s*[、，]", "、", part).strip("、， ")
        if part:
            cleaned.append(part)
    return "；".join(cleaned)


def registration(args: argparse.Namespace, number: str) -> dict[str, str | bool]:
    raw_text = args.traits_file.read_text(encoding="utf-8") if args.traits_file and args.traits_file.is_file() else args.traits
    if not (args.source_name or raw_text.strip()):
        raise ValueError("IMAGE_ONLY: image-only style imports belong to Tweet Style Importer.")
    traits = " ".join(raw_text.split()) if args.raw_traits else positive_traits(raw_text)
    return {
        "number": number,
        "source_name": args.source_name or "自创文本定义风格",
        "generation_name": args.generation_name or args.source_name or f"Original Text-Defined Style {number}",
        "traits": traits,
        "name_activation": "weak" if traits else "strong",
        "traits_activation": "strong" if traits else "none",
        "use_reference_image": False,
    }


def main() -> None:
    args = parse_args()
    number = get_next_style_number()
    try:
        record = registration(args, number)
    except ValueError as error:
        raise SystemExit(str(error)) from error
    if args.dry_run:
        print(json.dumps(record, ensure_ascii=False))
        return
    if not args.image:
        raise SystemExit("A representative image is required. Generate one 1:1 image first, then rerun with --image.")
    if not args.image.is_file():
        raise SystemExit(f"Representative image does not exist: {args.image}")

    assets = create_style_assets(number, [args.image], number)
    update_markdown_source(number, str(record["source_name"]), str(record["generation_name"]), str(record["traits"]))
    update_model_capabilities(number, name_activation=str(record["name_activation"]),
                              traits_activation=str(record["traits_activation"]))
    update_readme_and_skill(number)
    update_manifest(number)
    rebuild_and_validate()

    print(json.dumps({
        **record,
        "single_path": str(assets["tile"]),
        "grid_path": str(assets["grid"]) if assets["grid"] else None,
        "sheet_path": str(assets["sheet"]),
    }, ensure_ascii=False))


if __name__ == "__main__":
    main()
